version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: teamcalendar-mysql
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: teamcalendar
    volumes:
      - ./mysql-data:/var/lib/mysql
